# Configuration file

[audio]
s_rate = 16000
s_len = 64000
frame_size = 1024
hop_size = 512
conv_mod = 'same'

[json]
fname = 'info.json'
save_steps = 40

[logger]
level = 'debug'
#fname = 'history.log'

[neuralnet]
optimizer = 'sgd'
loss = 'mse'
batch_size = 32
epochs = 1

[demo]
datasets_url = 'https://raw.githubusercontent.com/polochinoc/various-audio-datasets/master/'
dnames = ['dry', 'fx', 'wet']
size = 'tiny'